version: "2"
services: 
  jenkins:
    image: 'docker.io/bitnami/jenkins:2-debian-10'
    environment: 
      JENKINS_SLAVE_AGENT_PORT: "50000"
    ports: 
      - "8080:8080"
      - "50000:50000"
      - "5000:5000"
    volumes: 
      - "/home/ubuntu/Jenkins:/var/jenkins_home"