version: "2.0"
services: 
  jenkins: 
    build: 
      context: "."
    environment: 
      JAVA_OPTS: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York"
      JENKINS_SLAVE_AGENT_PORT: "50000"
    ports: 
      - "8080:8080"
      - "50000:50000"
      - "5000:5000"
    volumes: 
      - "/home/ubuntu/Jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"