version: '2.0'
services:
   jenkins:
      build:
         context: .
      environment:
         JENKINS_SLAVE_AGENT_PORT: "50000"
         JAVA_OPTS: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York"
      ports:
         #host:container
         - "8080:8080" 
         - "50000:50000"
         - "5000:5000"
      volumes:
         - /home/ubuntu/Jenkins:/var/jenkins_home     # Set the Jenkins home on the host machine
         - /var/run/docker.sock:/var/run/docker.sock        # Allow the container to run Docker on Docker
